version: '0.9.5.{build}'
skip_non_tags: true
branches:
  only:
    - master

image: Visual Studio 2019

platform:
  - x64

configuration:
  - Release

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - vcpkg install curl[core,brotli,winssl]:x64-windows-static
  - git submodule update --init --recursive

before_build:
  - cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\arcdps_uploader.sln

after_build:
  - 7z a arcdps_uploader_%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Release\d3d9_uploader.dll %APPVEYOR_BUILD_FOLDER%\LICENSE 

artifacts:
  - path: arcdps_uploader_%APPVEYOR_BUILD_VERSION%.zip
    name: ArcdpsUploader

deploy:
    release: arcdps_uploader_v$(APPVEYOR_BUILD_VERSION)
    description: "Release"
    provider: GitHub
    auth_token:
        secure: I5j/uafQLh5Nz5MkQcWkgXJ8A7QULV79RhxFDxd95URUPMXxOYsL4jPuWw70BA43
    artifact: /.*\.zip/
    draft: true
    prerelase: false
    on:
        branch: master
