name: build
on: [push]
jobs:
  build:
    runs-on: windows-2019
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '${{ env.VCPKG_INSTALLATION_ROOT }}'
      - name: Run CMake
        uses: lukka/run-cmake@v10
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: Release/d3d9_uploader.dll
